### ISSUE TITLE
usb modem

### ISSUE THREAD

**Issue by mickey167** [FaceyComputers/Intercom-Audioplayer#7]
https://www.amazon.ca/gp/product/B00XW5QYWS/ref=s9u_simh_gw_i1?ie=UTF8&pd_rd_i=B00XW5QYWS&pd_rd_r=a4334c13-dacf-11e7-a93f-53683bc212b0&pd_rd_w=kJg66&pd_rd_wg=k1wOe&pf_rd_m=A3DWYIK6Y9EEQB&pf_rd_s=&pf_rd_r=CG3RKV306S8YHS0341CX&pf_rd_t=36701&pf_rd_p=07871b8e-d32a-4963-b98f-ba712077f7f5&pf_rd_i=desktop

will this work?  Was reading about windows compatability issues, and wasn't sure about what you are doing with it.

**Comment by ha0511kr** [comment]
Nope, please don't buy any modem cards. The telephone is actually digital
not analog so this won't work

**Comment by ha0511kr** [comment]
And there is no way to rewire that line because that RJ-11 is 6 pin not 2 pin nor 4. It's all proprietary
